- name: pki directory
  gather_facts: false
  vars:
    USER: securiport
    HOST0: 192.168.40.88
    HOST1: 192.168.40.89
    HOST2: 192.168.40.90
    
  hosts: etcd03
  gather_facts: false
  tasks: 
    - name: change pki groupe own
      file:
        path: pki
        owner: root
        group: root
        recurse: yes 
    - name: creating kubernetes directory
      file:
        path: /etc/kubernetes
        state: directory
        mode: '0755'

    - name: move pki folder
      command: mv pki /etc/kubernetes/pki
      args:
        chdir: /home/securiport/
       
- name: pki directory
  hosts: etcd02
  gather_facts: false
  tasks: 
    - name: change pki groupe own
      file:
        path: pki
        owner: root
        group: root
        recurse: yes 
    - name: creating kubernetes directory
      file:
        path: /etc/kubernetes
        state: directory
        mode: '0755'

    - name: move pki folder
      command: mv pki /etc/kubernetes/pki
      args:
        chdir: /home/securiport/

- name: init phase etcd local etcd01
  hosts: etcd01
  gather_facts: false
  tasks: 
    - name: init phase etcd local etcd01
      command: kubeadm init phase etcd local --config=/tmp/{{ HOST0 }}/kubeadmcfg.yaml

- name: init phase etcd local etcd01
  hosts: etcd02
  gather_facts: false
  tasks: 
    - name: init phase etcd local etcd02
      command: kubeadm init phase etcd local --config=/home/securiport/kubeadmcfg.yaml

- name: init phase etcd local etcd03
  hosts: etcd03
  gather_facts: false
  tasks: 
    - name: init phase etcd local etcd03
      command: kubeadm init phase etcd local --config=/home/securiport/kubeadmcfg.yaml