---
- name: initialize cluster
  hosts: master01
  tasks:
    - name: pull images
      become: yes
      command:
        cmd: kubeadm config images pull
      register: __output

    - name: Creating kubeadm configuracion file
      become: yes
      set_fact:
        kubeadm_config_content: |
          apiVersion: kubeadm.k8s.io/v1beta3
          kind: InitConfiguration
          nodeRegistration:
            kubeletExtraArgs:
              volume-plugin-dir: "/opt/libexec/kubernetes/kubelet-plugins/volume/exec/"
          ---
          apiVersion: kubeadm.k8s.io/v1beta3
          kind: ClusterConfiguration
          networking:
            podSubnet: 192.168.0.0/16
          clusterName: lab-cluster
          controlPlaneEndpoint: "192.168.40.51:6443"
          controllerManager:
            extraArgs:
              flex-volume-plugin-dir: "/opt/libexec/kubernetes/kubelet-plugins/volume/exec/"
      
    - name: Creating kubeadm configuracion file on home directory
      become: yes
      copy:
        content: "{{ kubeadm_config_content }}"
        dest: /home/securiport/kubeadm-config.yaml
     #   backup: yes

    - name: kubeadm init --config kubeadm-config.yaml
      become: yes
      shell: "kubeadm init --config /home/securiport/kubeadm-config.yaml >> node_joined.txt"
      args:
        chdir: $HOME
        creates: node_joined.txt

    - name: Creating calico configuracion file
      become: yes
      set_fact:
        calico_content: |
          # Source: https://docs.projectcalico.org/manifests/custom-resources.yaml
          apiVersion: operator.tigera.io/v1
          kind: Installation
          metadata:
            name: default
          spec:
            # Configures Calico networking.
            calicoNetwork:
              # Note: The ipPools section cannot be modified post-install.
              ipPools:
              - blockSize: 26
                cidr: 192.168.0.0/16
                encapsulation: VXLANCrossSubnet
                natOutgoing: Enabled
                nodeSelector: all()
              flexVolumePath: /opt/libexec/kubernetes/kubelet-plugins/volume/exec/
      
    - name: Creating calico configuracion file on home directory
      become: yes
      copy:
        content: "{{ calico_content }}"
        dest: /home/securiport/calico.yaml
        backup: yes

    - name: creating .kube directory
      become: yes
      file:
        path: /home/securiport/.kube
        state: directory
        mode : 0755

    - name: copy file admin.conf 
      become: yes
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/securiport/.kube/config
        remote_src: yes
        mode : 0600