- name: Generate kubeadmcfg.yaml
  hosts: etcd01
  gather_facts: false

  vars:
    HOST0: 192.168.40.88
    HOST1: 192.168.40.89
    HOST2: 192.168.40.90
    NAME0: etcd01
    NAME1: etcd02
    NAME2: etcd03
    HOSTS:
      - "{{ HOST0 }}"
      - "{{ HOST1 }}"
      - "{{ HOST2 }}"
    NAMES:
      - "{{ NAME0 }}"
      - "{{ NAME1 }}"
      - "{{ NAME2 }}"
#    NAMES: "{{ NAMES[loop.index0] }}"
  tasks:
    - name: Creating kubeadmcfg.yaml file
      copy:
        content: |
          [Service]
          ExecStart=
          # Replace "systemd" with the cgroup driver of your container runtime. The default value in the kubelet is "cgroupfs".
          # Replace the value of "--container-runtime-endpoint" for a different container runtime if needed.
          ExecStart=/opt/bin/kubelet --address=127.0.0.1 --pod-manifest-path=/etc/kubernetes/manifests --cgroup-driver=systemd --container-runtime=remote --container-runtime-endpoint=unix:///var/run/containerd/containerd.sock
          Restart=always
        dest: "/etc/systemd/system/kubelet.service.d/20-etcd-service-manager.conf"

    - name: activate kubelet
      shell: |
        systemctl daemon-reload
        systemctl restart kubelet
        systemctl status kubelet
    - name: creating etcd01 directory
      become: yes
      file:
        path: /tmp/{{ HOST0 }}/
        state: directory

    - name: creating etcd02 directory
      become: yes
      file:
        path: /tmp/{{ HOST1 }}/
        state: directory

    - name: creating etcd03 directory
      become: yes
      file:
        path: /tmp/{{ HOST2 }}/
        state: directory

    - name: Create kubeadmcfg.yaml file
      copy:
        content: |
          ---
          apiVersion: "kubeadm.k8s.io/v1beta3"
          kind: InitConfiguration
          nodeRegistration:
              name: "{{ item }}"
          localAPIEndpoint:
              advertiseAddress: {{ item }}
          ---
          apiVersion: "kubeadm.k8s.io/v1beta3"
          kind: ClusterConfiguration
          etcd:
              local:
                  serverCertSANs:
                  - "{{ item }}"
                  peerCertSANs:
                  - "{{ item }}"
                  extraArgs:
                      initial-cluster: {{ NAMES[0] }}=https://{{ HOSTS[0] }}:2380,{{ NAMES[1] }}=https://{{ HOSTS[1] }}:2380,{{ NAMES[2] }}=https://{{ HOSTS[2] }}:2380
                      initial-cluster-state: new
                      name: {{ item }}
                      listen-peer-urls: https://{{ item }}:2380
                      listen-client-urls: https://{{ item }}:2379
                      advertise-client-urls: https://{{ item }}:2379
                      initial-advertise-peer-urls: https://{{ item }}:2380
        dest: "/tmp/{{ item }}/kubeadmcfg.yaml"
      loop: "{{ HOSTS }}"
      become: true