- name: Join masters
  hosts: master01
  become: yes
  tasks:
 
    - name: add masters
      shell: sed -n '71,73p' node_joined.txt
      register: join_master

    - name: set join command
      set_fact:
        join_command: "{{ join_master.stdout_lines[0] }}"

- name: Joining masters
  hosts: master
  become: yes
  tasks:
    - name: join cluster
      shell: "{{ hostvars['master01'].join_command }} --ignore-preflight-errors all  >> node_joined.txt"
      args:
        chdir: $HOME
        creates: master_joined.txt

- name: Joining masters
  hosts: master01
  tasks:
    - name: install Tigera
      shell: |
        kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.26.0/manifests/tigera-operator.yaml

    - name: Downloading calico using get_url
      become: yes
      get_url:
        url: https://raw.githubusercontent.com/projectcalico/calico/v3.26.0/manifests/custom-resources.yaml -O
        dest: /home/securiport

    - name: install Calico
      shell: |
       kubectl create -f /home/securiport/custom-resources.yaml

    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

- name: Join workers
  hosts: workers
  become: yes
  tasks:
    - name: join cluster
      shell: "{{ hostvars['master01'].join_command }} --ignore-preflight-errors all  >> node_joined.txt"
      args:
        chdir: $HOME
        creates: node_joined.txt
